name: 'Download a Build Artifact'
description: 'Download a build artifact that was previously uploaded in the workflow by the upload-artifact action'
author: 'GitHub'
inputs: 
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'Destination path'
    required: false
outputs:
  download-path:
    description: 'Path of artifact download'
  artifact-found:
    description: 'Set when artifact found'

runs:
  using: 'node16'
  main: 'dist/index.js'
